spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://115.93.26.228:3306/hmi
    username: root
    password: iot123!
logging:
  level:
    root: info
    com.hmi: debug